export const THROTTLE_DURATION = 750;

export const BATCH_PROCESSING_INTERVAL_MS = 500;
export const COSMO_BATCH_PROCESSING_INTERVAL_MS = 1000;

export const HOLDINGS_BATCH_PROCESSING_INTERVAL_MS = 500;
export const HOLDINGS_CHART_PRICE_BATCH_PROCESSING_INTERVAL_MS = 350;

export const TRANSACTION_BATCH_PROCESSING_INTERVAL_MS = 400;
