export const defaultTVChartProperties = {
  timezone: "Etc/UTC",
  priceScaleSelectionStrategyName: "auto",
  paneProperties: {
    backgroundType: "solid",
    background: "#080812",
    backgroundGradientStartColor: "#181C27",
    backgroundGradientEndColor: "#131722",
    gridLinesMode: "both",
    vertGridProperties: {
      color: "#1a1a2e",
      style: 0,
    },
    horzGridProperties: {
      color: "#1a1a2e",
      style: 0,
    },
    crossHairProperties: {
      color: "#9598A1",
      style: 2,
      transparency: 0,
      width: 1,
    },
    topMargin: 10,
    bottomMargin: 8,
    axisProperties: {
      autoScale: true,
      autoScaleDisabled: false,
      lockScale: false,
      percentage: false,
      percentageDisabled: false,
      indexedTo100: false,
      log: false,
      logDisabled: false,
      alignLabels: true,
      isInverted: false,
    },
    legendProperties: {
      showStudyArguments: true,
      showStudyTitles: true,
      showStudyValues: true,
      showSeriesTitle: true,
      showSeriesOHLC: true,
      showLegend: true,
      showLastDayChange: false,
      showBarChange: true,
      showVolume: false,
      showBackground: true,
      showPriceSource: true,
      backgroundTransparency: 50,
      showLogo: true,
    },
    separatorColor: "#2A2E39",
  },
  scalesProperties: {
    backgroundColor: "#ffffff",
    lineColor: "rgba(240, 243, 250, 0)",
    textColor: "#B2B5BE",
    fontSize: 12,
    scaleSeriesOnly: false,
    showSeriesLastValue: true,
    seriesLastValueMode: 1,
    showSeriesPrevCloseValue: false,
    showStudyLastValue: true,
    showSymbolLabels: false,
    showStudyPlotLabels: false,
    showBidAskLabels: false,
    showPrePostMarketPriceLabel: true,
    showFundamentalNameLabel: false,
    showFundamentalLastValue: true,
    barSpacing: 6,
  },
  mainSeriesProperties: {
    style: 1,
    esdShowDividends: true,
    esdShowSplits: true,
    esdShowEarnings: true,
    esdShowBreaks: false,
    esdFlagSize: 2,
    showContinuousContractSwitches: true,
    showContinuousContractSwitchesBreaks: false,
    showFuturesContractExpiration: true,
    showLastNews: true,
    showCountdown: false,
    bidAsk: {
      visible: false,
      lineStyle: 1,
      lineWidth: 1,
      bidLineColor: "#2962FF",
      askLineColor: "#F7525F",
    },
    prePostMarket: {
      visible: true,
      lineStyle: 1,
      lineWidth: 1,
      preMarketColor: "#FB8C00",
      postMarketColor: "#2962FF",
    },
    highLowAvgPrice: {
      highLowPriceLinesVisible: false,
      highLowPriceLabelsVisible: false,
      averageClosePriceLineVisible: false,
      averageClosePriceLabelVisible: false,
      highLowPriceLinesColor: "",
      highLowPriceLinesWidth: 1,
      averagePriceLineColor: "",
      averagePriceLineWidth: 1,
    },
    visible: true,
    showPriceLine: true,
    priceLineWidth: 1,
    priceLineColor: "",
    baseLineColor: "#B2B5BE",
    showPrevClosePriceLine: false,
    prevClosePriceLineWidth: 1,
    prevClosePriceLineColor: "#555555",
    minTick: "default",
    dividendsAdjustment: {},
    backAdjustment: false,
    settlementAsClose: true,
    sessionId: "regular",
    sessVis: false,
    statusViewStyle: {
      fontSize: 16,
      showExchange: true,
      showInterval: true,
      symbolTextSource: "description",
    },
    candleStyle: {
      upColor: "#8CD9B6",
      downColor: "#F65B93",
      drawWick: true,
      drawBorder: true,
      borderColor: "#8CD9B6",
      borderUpColor: "#8CD9B6",
      borderDownColor: "#F65B93",
      wickColor: "#8CD9B6",
      wickUpColor: "#8CD9B6",
      wickDownColor: "#F65B93",
      barColorsOnPrevClose: false,
      drawBody: true,
    },
    volCandlesStyle: {
      upColor: "#8CD9B6",
      downColor: "#F65B93",
      drawWick: true,
      drawBorder: true,
      borderColor: "#8CD9B6",
      borderUpColor: "#8CD9B6",
      borderDownColor: "#F65B93",
      wickColor: "#8CD9B6",
      wickUpColor: "#8CD9B6",
      wickDownColor: "#F65B93",
      barColorsOnPrevClose: false,
      drawBody: true,
    },
    hollowCandleStyle: {
      upColor: "#8CD9B6",
      downColor: "#F65B93",
      drawWick: true,
      drawBorder: true,
      borderColor: "#8CD9B6",
      borderUpColor: "#8CD9B6",
      borderDownColor: "#F65B93",
      wickColor: "#8CD9B6",
      wickUpColor: "#8CD9B6",
      wickDownColor: "#F65B93",
      drawBody: true,
    },
    haStyle: {
      upColor: "#8CD9B6",
      downColor: "#F65B93",
      drawWick: true,
      drawBorder: true,
      borderColor: "#8CD9B6",
      borderUpColor: "#8CD9B6",
      borderDownColor: "#F65B93",
      wickColor: "#8CD9B6",
      wickUpColor: "#8CD9B6",
      wickDownColor: "#F65B93",
      showRealLastPrice: false,
      barColorsOnPrevClose: false,
      inputs: {},
      inputInfo: {},
      drawBody: true,
    },
    barStyle: {
      upColor: "#8CD9B6",
      downColor: "#F65B93",
      barColorsOnPrevClose: false,
      dontDrawOpen: false,
      thinBars: true,
    },
    hiloStyle: {
      color: "#2962FF",
      showBorders: true,
      borderColor: "#2962FF",
      showLabels: true,
      labelColor: "#2962FF",
      drawBody: true,
    },
    columnStyle: {
      upColor: "rgba(8, 153, 129, 0.5)",
      downColor: "rgba(242, 54, 69, 0.5)",
      barColorsOnPrevClose: true,
      priceSource: "close",
      baselinePosition: "bottom",
    },
    lineStyle: {
      color: "#2962FF",
      linestyle: 0,
      linewidth: 2,
      priceSource: "close",
    },
    tpoStyle: {},
    svpStyle: {},
    lineWithMarkersStyle: {
      color: "#2962FF",
      linestyle: 0,
      linewidth: 2,
      priceSource: "close",
    },
    steplineStyle: {
      color: "#2962FF",
      linestyle: 0,
      linewidth: 2,
      priceSource: "close",
    },
    areaStyle: {
      color1: "rgba(41, 98, 255, 0.28)",
      color2: "#2962FF",
      linecolor: "#2962FF",
      linestyle: 0,
      linewidth: 2,
      priceSource: "close",
      transparency: 100,
    },
    hlcAreaStyle: {
      highLineColor: "#8CD9B6",
      highLineStyle: 0,
      highLineWidth: 2,
      lowLineColor: "#F65B93",
      lowLineStyle: 0,
      lowLineWidth: 2,
      closeLineColor: "#868993",
      closeLineStyle: 0,
      closeLineWidth: 2,
      highCloseFillColor: "rgba(8, 153, 129, 0.2)",
      closeLowFillColor: "rgba(242, 54, 69, 0.2)",
    },
    priceAxisProperties: {
      autoScale: true,
      autoScaleDisabled: false,
      lockScale: false,
      percentage: false,
      percentageDisabled: false,
      indexedTo100: false,
      log: false,
      logDisabled: false,
      isInverted: false,
      alignLabels: true,
    },
    renkoStyle: {
      upColor: "#8CD9B6",
      downColor: "#F65B93",
      borderUpColor: "#8CD9B6",
      borderDownColor: "#F65B93",
      upColorProjection: "#a9dcc3",
      downColorProjection: "#f5a6ae",
      borderUpColorProjection: "#a9dcc3",
      borderDownColorProjection: "#f5a6ae",
      wickUpColor: "#8CD9B6",
      wickDownColor: "#F65B93",
      inputs: {
        source: "close",
        sources: "Close",
        boxSize: 3,
        style: "ATR",
        atrLength: 14,
        percentageLTP: 1,
        wicks: true,
      },
      inputInfo: {
        source: {
          name: "Source",
        },
        sources: {
          name: "Source",
        },
        boxSize: {
          name: "Box size",
        },
        style: {
          name: "Style",
        },
        atrLength: {
          name: "ATR length",
        },
        percentageLTP: {
          name: "Percentage",
        },
        wicks: {
          name: "Wicks",
        },
      },
    },
    pbStyle: {
      upColor: "#8CD9B6",
      downColor: "#F65B93",
      borderUpColor: "#8CD9B6",
      borderDownColor: "#F65B93",
      upColorProjection: "#a9dcc3",
      downColorProjection: "#f5a6ae",
      borderUpColorProjection: "#a9dcc3",
      borderDownColorProjection: "#f5a6ae",
      inputs: {
        source: "close",
        lb: 3,
      },
      inputInfo: {
        source: {
          name: "Source",
        },
        lb: {
          name: "Number of line",
        },
      },
    },
    kagiStyle: {
      upColor: "#8CD9B6",
      downColor: "#F65B93",
      upColorProjection: "#a9dcc3",
      downColorProjection: "#f5a6ae",
      inputs: {
        source: "close",
        style: "ATR",
        atrLength: 14,
        percentageLTP: 1,
        reversalAmount: 1,
      },
      inputInfo: {
        source: {
          name: "Source",
        },
        style: {
          name: "Style",
        },
        atrLength: {
          name: "ATR length",
        },
        percentageLTP: {
          name: "Percentage",
        },
        reversalAmount: {
          name: "Reversal amount",
        },
      },
    },
    pnfStyle: {
      upColor: "#8CD9B6",
      downColor: "#F65B93",
      upColorProjection: "#a9dcc3",
      downColorProjection: "#f5a6ae",
      inputs: {
        sources: "Close",
        reversalAmount: 3,
        boxSize: 1,
        style: "ATR",
        atrLength: 14,
        percentageLTP: 1,
        oneStepBackBuilding: false,
      },
      inputInfo: {
        sources: {
          name: "Source",
        },
        boxSize: {
          name: "Box size",
        },
        reversalAmount: {
          name: "Reversal amount",
        },
        style: {
          name: "Style",
        },
        atrLength: {
          name: "ATR length",
        },
        percentageLTP: {
          name: "Percentage",
        },
        oneStepBackBuilding: {
          name: "One step back building",
        },
      },
    },
    baselineStyle: {
      baselineColor: "#868993",
      topFillColor1: "rgba(8, 153, 129, 0.28)",
      topFillColor2: "rgba(8, 153, 129, 0.05)",
      bottomFillColor1: "rgba(242, 54, 69, 0.05)",
      bottomFillColor2: "rgba(242, 54, 69, 0.28)",
      topLineColor: "#8CD9B6",
      bottomLineColor: "#F65B93",
      topLineWidth: 2,
      bottomLineWidth: 2,
      priceSource: "close",
      transparency: 50,
      baseLevelPercentage: 50,
    },
    rangeStyle: {
      barStyle: 0,
      upColor: "#8CD9B6",
      downColor: "#F65B93",
      upColorProjection: "#a9dcc3",
      downColorProjection: "#f5a6ae",
      thinBars: true,
      candlesUpColor: "#8CD9B6",
      candlesDownColor: "#F65B93",
      candlesBorderUpColor: "#8CD9B6",
      candlesBorderDownColor: "#F65B93",
      candlesWickUpColor: "#8CD9B6",
      candlesWickDownColor: "#F65B93",
      inputs: {
        range: 10,
        phantomBars: false,
      },
      inputInfo: {
        range: {
          name: "Range",
        },
        phantomBars: {
          name: "Phantom bars",
        },
      },
    },
    volFootprintStyle: {},
    symbol: "3zd7UsRiUzhhJf1ngxQ23GNpzWqPwjeWqu7iMbfRpump",
    shortName: "",
    timeframe: "",
    onWidget: false,
    interval: "1S",
    currencyId: null,
    unitId: null,
  },
  chartEventsSourceProperties: {
    visible: true,
    futureOnly: true,
    breaks: {
      color: "#555555",
      visible: false,
      style: 2,
      width: 1,
    },
  },
  tradingProperties: {
    showPositions: true,
    positionPL: {
      visibility: true,
      display: 0,
    },
    bracketsPL: {
      visibility: true,
      display: 0,
    },
    showOrders: true,
    showExecutions: true,
    showExecutionsLabels: false,
    showReverse: true,
    horizontalAlignment: 2,
    extendLeft: true,
    lineLength: 5,
    lineWidth: 1,
    lineStyle: 0,
  },
  editorFontsList: {
    "0": "Verdana",
    "1": "Courier New",
    "2": "Times New Roman",
    "3": "Arial",
  },
  volumePaneSize: "large",
};

export const defaultTVChartPropertiesMainSeriesProperties = {
  style: 1,
  esdShowDividends: true,
  esdShowSplits: true,
  esdShowEarnings: true,
  esdShowBreaks: false,
  esdFlagSize: 2,
  showContinuousContractSwitches: true,
  showContinuousContractSwitchesBreaks: false,
  showFuturesContractExpiration: true,
  showLastNews: true,
  showCountdown: false,
  bidAsk: {
    visible: false,
    lineStyle: 1,
    lineWidth: 1,
    bidLineColor: "#2962FF",
    askLineColor: "#F7525F",
  },
  prePostMarket: {
    visible: true,
    lineStyle: 1,
    lineWidth: 1,
    preMarketColor: "#FB8C00",
    postMarketColor: "#2962FF",
  },
  highLowAvgPrice: {
    highLowPriceLinesVisible: false,
    highLowPriceLabelsVisible: false,
    averageClosePriceLineVisible: false,
    averageClosePriceLabelVisible: false,
    highLowPriceLinesColor: "",
    highLowPriceLinesWidth: 1,
    averagePriceLineColor: "",
    averagePriceLineWidth: 1,
  },
  showPriceLine: true,
  priceLineWidth: 1,
  priceLineColor: "",
  baseLineColor: "#5d606b",
  showPrevClosePriceLine: false,
  prevClosePriceLineWidth: 1,
  prevClosePriceLineColor: "#555555",
  minTick: "default",
  dividendsAdjustment: {},
  backAdjustment: false,
  settlementAsClose: true,
  sessionId: "regular",
  sessVis: false,
  statusViewStyle: {
    fontSize: 16,
    showExchange: true,
    showInterval: true,
    symbolTextSource: "description",
  },
  candleStyle: {
    upColor: "#8CD9B6",
    downColor: "#F65B93",
    drawWick: true,
    drawBorder: true,
    borderColor: "#8CD9B6",
    borderUpColor: "#8CD9B6",
    borderDownColor: "#F65B93",
    wickColor: "#8CD9B6",
    wickUpColor: "#8CD9B6",
    wickDownColor: "#F65B93",
    barColorsOnPrevClose: false,
    drawBody: true,
  },
  volCandlesStyle: {
    upColor: "#8CD9B6",
    downColor: "#F65B93",
    drawWick: true,
    drawBorder: true,
    borderColor: "#8CD9B6",
    borderUpColor: "#8CD9B6",
    borderDownColor: "#F65B93",
    wickColor: "#8CD9B6",
    wickUpColor: "#8CD9B6",
    wickDownColor: "#F65B93",
    barColorsOnPrevClose: false,
    drawBody: true,
  },
  hollowCandleStyle: {
    upColor: "#8CD9B6",
    downColor: "#F65B93",
    drawWick: true,
    drawBorder: true,
    borderColor: "#8CD9B6",
    borderUpColor: "#8CD9B6",
    borderDownColor: "#F65B93",
    wickColor: "#8CD9B6",
    wickUpColor: "#8CD9B6",
    wickDownColor: "#F65B93",
    drawBody: true,
  },
  haStyle: {
    upColor: "#8CD9B6",
    downColor: "#F65B93",
    drawWick: true,
    drawBorder: true,
    borderColor: "#8CD9B6",
    borderUpColor: "#8CD9B6",
    borderDownColor: "#F65B93",
    wickColor: "#8CD9B6",
    wickUpColor: "#8CD9B6",
    wickDownColor: "#F65B93",
    showRealLastPrice: false,
    barColorsOnPrevClose: false,
    inputs: {},
    inputInfo: {},
    drawBody: true,
  },
  barStyle: {
    upColor: "#8CD9B6",
    downColor: "#F65B93",
    barColorsOnPrevClose: false,
    dontDrawOpen: false,
    thinBars: true,
  },
  hiloStyle: {
    color: "#2962FF",
    showBorders: true,
    borderColor: "#2962FF",
    showLabels: true,
    labelColor: "#2962FF",
    drawBody: true,
  },
  columnStyle: {
    upColor: "rgba(8, 153, 129, 0.5)",
    downColor: "rgba(242, 54, 69, 0.5)",
    barColorsOnPrevClose: true,
    priceSource: "close",
    baselinePosition: "bottom",
  },
  lineStyle: {
    color: "#2962FF",
    linestyle: 0,
    linewidth: 2,
    priceSource: "close",
  },
  tpoStyle: {},
  svpStyle: {},
  lineWithMarkersStyle: {
    color: "#2962FF",
    linestyle: 0,
    linewidth: 2,
    priceSource: "close",
  },
  steplineStyle: {
    color: "#2962FF",
    linestyle: 0,
    linewidth: 2,
    priceSource: "close",
  },
  areaStyle: {
    color1: "rgba(41, 98, 255, 0.28)",
    color2: "#2962FF",
    linecolor: "#2962FF",
    linestyle: 0,
    linewidth: 2,
    priceSource: "close",
    transparency: 100,
  },
  hlcAreaStyle: {
    highLineColor: "#8CD9B6",
    highLineStyle: 0,
    highLineWidth: 2,
    lowLineColor: "#F65B93",
    lowLineStyle: 0,
    lowLineWidth: 2,
    closeLineColor: "#868993",
    closeLineStyle: 0,
    closeLineWidth: 2,
    highCloseFillColor: "rgba(8, 153, 129, 0.2)",
    closeLowFillColor: "rgba(242, 54, 69, 0.2)",
  },
  renkoStyle: {
    upColor: "#8CD9B6",
    downColor: "#F65B93",
    borderUpColor: "#8CD9B6",
    borderDownColor: "#F65B93",
    upColorProjection: "#336854",
    downColorProjection: "#7f323f",
    borderUpColorProjection: "#336854",
    borderDownColorProjection: "#7f323f",
    wickUpColor: "#8CD9B6",
    wickDownColor: "#F65B93",
    inputs: {
      source: "close",
      sources: "Close",
      boxSize: 3,
      style: "ATR",
      atrLength: 14,
      percentageLTP: 1,
      wicks: true,
    },
    inputInfo: {
      source: {
        name: "Source",
      },
      sources: {
        name: "Source",
      },
      boxSize: {
        name: "Box size",
      },
      style: {
        name: "Style",
      },
      atrLength: {
        name: "ATR length",
      },
      percentageLTP: {
        name: "Percentage",
      },
      wicks: {
        name: "Wicks",
      },
    },
  },
  pbStyle: {
    upColor: "#8CD9B6",
    downColor: "#F65B93",
    borderUpColor: "#8CD9B6",
    borderDownColor: "#F65B93",
    upColorProjection: "#336854",
    downColorProjection: "#7f323f",
    borderUpColorProjection: "#336854",
    borderDownColorProjection: "#7f323f",
    inputs: {
      source: "close",
      lb: 3,
    },
    inputInfo: {
      source: {
        name: "Source",
      },
      lb: {
        name: "Number of line",
      },
    },
  },
  kagiStyle: {
    upColor: "#8CD9B6",
    downColor: "#F65B93",
    upColorProjection: "#336854",
    downColorProjection: "#7f323f",
    inputs: {
      source: "close",
      style: "ATR",
      atrLength: 14,
      percentageLTP: 1,
      reversalAmount: 1,
    },
    inputInfo: {
      source: {
        name: "Source",
      },
      style: {
        name: "Style",
      },
      atrLength: {
        name: "ATR length",
      },
      percentageLTP: {
        name: "Percentage",
      },
      reversalAmount: {
        name: "Reversal amount",
      },
    },
  },
  pnfStyle: {
    upColor: "#8CD9B6",
    downColor: "#F65B93",
    upColorProjection: "#336854",
    downColorProjection: "#7f323f",
    inputs: {
      sources: "Close",
      reversalAmount: 3,
      boxSize: 1,
      style: "ATR",
      atrLength: 14,
      percentageLTP: 1,
      oneStepBackBuilding: false,
    },
    inputInfo: {
      sources: {
        name: "Source",
      },
      boxSize: {
        name: "Box size",
      },
      reversalAmount: {
        name: "Reversal amount",
      },
      style: {
        name: "Style",
      },
      atrLength: {
        name: "ATR length",
      },
      percentageLTP: {
        name: "Percentage",
      },
      oneStepBackBuilding: {
        name: "One step back building",
      },
    },
  },
  baselineStyle: {
    baselineColor: "#758696",
    topFillColor1: "rgba(8, 153, 129, 0.28)",
    topFillColor2: "rgba(8, 153, 129, 0.05)",
    bottomFillColor1: "rgba(242, 54, 69, 0.05)",
    bottomFillColor2: "rgba(242, 54, 69, 0.28)",
    topLineColor: "#8CD9B6",
    bottomLineColor: "#F65B93",
    topLineWidth: 2,
    bottomLineWidth: 2,
    priceSource: "close",
    transparency: 50,
    baseLevelPercentage: 50,
  },
  rangeStyle: {
    barStyle: 0,
    upColor: "#8CD9B6",
    downColor: "#F65B93",
    upColorProjection: "#336854",
    downColorProjection: "#7f323f",
    thinBars: true,
    candlesUpColor: "#8CD9B6",
    candlesDownColor: "#F65B93",
    candlesBorderUpColor: "#8CD9B6",
    candlesBorderDownColor: "#F65B93",
    candlesWickUpColor: "#8CD9B6",
    candlesWickDownColor: "#F65B93",
    inputs: {
      range: 10,
      phantomBars: false,
    },
    inputInfo: {
      range: {
        name: "Range",
      },
      phantomBars: {
        name: "Phantom bars",
      },
    },
  },
  volFootprintStyle: {},
  symbol: "3zd7UsRiUzhhJf1ngxQ23GNpzWqPwjeWqu7iMbfRpump",
  shortName: "",
  timeframe: "",
  onWidget: false,
  interval: "1S",
  unitId: null,
  priceAxisProperties: {
    autoScale: true,
    alignLabels: true,
  },
};
